In [78]:
import pandas as pd
import numpy as np

In [79]:
data = pd.read_csv('fhs_train.csv')
data = data.drop('Unnamed: 0',axis=1)
data

,sex,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,58,1.0,0,0.0,0.0,0,0,0,220.0,143.0,104.0,29.85,75,87.0,1
1,0,40,1.0,1,15.0,0.0,0,0,0,199.0,122.0,82.0,22.16,85,77.0,0
2,0,52,1.0,0,0.0,0.0,0,0,0,275.0,112.0,71.0,25.68,80,NaN,0
3,1,38,2.0,1,43.0,0.0,0,1,0,170.0,130.0,94.0,23.90,110,75.0,0
4,0,43,1.0,0,0.0,0.0,0,0,0,202.0,124.0,92.0,21.26,75,74.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3175,1,36,4.0,0,0.0,0.0,0,0,0,234.0,133.0,88.0,26.78,58,100.0,0
3176,1,47,1.0,1,20.0,0.0,0,0,0,284.0,137.0,91.0,27.33,73,61.0,0
3177,1,52,2.0,0,0.0,0.0,0,0,0,310.0,135.0,89.0,29.51,64,74.0,1
3178,0,48,1.0,1,5.0,0.0,0,0,0,296.0,117.0,73.0,24.59,70,78.0,0
3179,0,60,2.0,1,15.0,0.0,0,1,0,236.0,183.0,107.0,25.45,86,NaN,0

In [80]:
columns = ['sex', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose', 'TenYearCHD']

In [81]:
# RESOURCES
# https://www.statology.org/pandas-select-rows-without-nan/

data = data[~data.isnull().any(axis=1)] # gets rid of all rows with np.nan values
data = data.rename(columns={"TenYearCHD": "TEN_YEAR_CHD"})
data.to_csv("fhs_train_cleaned.csv")
data

,sex,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TEN_YEAR_CHD
0,1,58,1.0,0,0.0,0.0,0,0,0,220.0,143.0,104.0,29.85,75,87.0,1
1,0,40,1.0,1,15.0,0.0,0,0,0,199.0,122.0,82.0,22.16,85,77.0,0
3,1,38,2.0,1,43.0,0.0,0,1,0,170.0,130.0,94.0,23.90,110,75.0,0
4,0,43,1.0,0,0.0,0.0,0,0,0,202.0,124.0,92.0,21.26,75,74.0,0
6,0,54,1.0,0,0.0,0.0,0,1,0,237.0,171.5,105.5,34.25,91,104.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3174,0,54,2.0,0,0.0,0.0,0,1,0,320.0,165.0,84.0,38.31,80,99.0,0
3175,1,36,4.0,0,0.0,0.0,0,0,0,234.0,133.0,88.0,26.78,58,100.0,0
3176,1,47,1.0,1,20.0,0.0,0,0,0,284.0,137.0,91.0,27.33,73,61.0,0
3177,1,52,2.0,0,0.0,0.0,0,0,0,310.0,135.0,89.0,29.51,64,74.0,1
3178,0,48,1.0,1,5.0,0.0,0,0,0,296.0,117.0,73.0,24.59,70,78.0,0